In [3]:
import numpy as np

arry = np.array([1,2,3,4,5,6,7,8,9])
print(arry)
print(type(arry))
print(arry.shape)#use for length 

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
(9,)


In [11]:
a=np.array([1,2,4,5,6,4,8,1,8,4,3,4,6])
a.reshape(1,13)

array([[1, 2, 4, 5, 6, 4, 8, 1, 8, 4, 3, 4, 6]])

In [129]:
array2= np.array([1,2,3,4,5])
array2.reshape(1,5)# 1 row 5 col

array([[1, 2, 3, 4, 5]])

In [7]:
array2= np.array([[1,2,3,4,5]])
array2.shape

(1, 5)

In [9]:
array2= np.array([[1,2,3,4,5],[56,654,47,49,61]])
print(array2.shape)
array2


(2, 5)


array([[  1,   2,   3,   4,   5],
       [ 56, 654,  47,  49,  61]])

In [11]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [25]:
array2= np.array([[1,2,3,4,5],[56,654,47,49,61]])
print('array',array2)
print('Shape',array2.shape)
print('number of dimention',array2.ndim)
print('size of elements',array2.size)
print('data-type',array2.dtype)
print('item size(in bytes)',array2.itemsize)

array [[  1   2   3   4   5]
 [ 56 654  47  49  61]]
Shape (2, 5)
number of dimention 2
size of elements 10
data-type int32
item size(in bytes) 4


In [28]:
array1=np.array([1,2,3,4,5])
array2=np.array([6,7,8,9,10])

print('addition:',array1+array2)


addition: [ 7  9 11 13 15]


In [32]:
a=np.array([2,3,4,55,32])
b=np.array([12,3,23,43,12])


print('Addition',a+b )

print('subtraction',a-b)

print('multiplication',a*b)

print('division',a/b)


Addition [14  6 27 98 44]
subtraction [-10   0 -19  12  20]
multiplication [  24    9   92 2365  384]
division [0.16666667 1.         0.17391304 1.27906977 2.66666667]


In [38]:
arra=np.array([1,2,3,4,5])

print(np.sqrt(arra))
                
print(np.sin(arra))

print(np.cos(arra))

[1.         1.41421356 1.73205081 2.         2.23606798]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


In [60]:
arru1=np.array([[1,2,3,4,5],[2,3,4,5,6],[23,45,4,3,343]])
print(arru1)


[[  1   2   3   4   5]
 [  2   3   4   5   6]
 [ 23  45   4   3 343]]


In [ ]:
arru1[0:2,0:2] #row #col




array([[1, 2],
       [2, 3]])

In [83]:
arru1=np.array([[1,2,3,4,5],[2,3,4,5,6],[23,45,4,3,343]])
print(arru1)
print('-----------------------')
arru1[0,0]= 100
print('-----------------------')
print(arru1)
print('-----------------------')
arru1[1:3]= 100
print(arru1)

[[  1   2   3   4   5]
 [  2   3   4   5   6]
 [ 23  45   4   3 343]]
-----------------------
-----------------------
[[100   2   3   4   5]
 [  2   3   4   5   6]
 [ 23  45   4   3 343]]
-----------------------
[[100   2   3   4   5]
 [100 100 100 100 100]
 [100 100 100 100 100]]


In [105]:
apta=np.array([1,2,3,4,5])
print(apta)
mean=np.mean(apta)
print('mean = ',mean)
print('Sorted =',np.sort(apta))
median = np.median(apta)
print('Median =',median)

std_dev =np.std(apta)
print('Standard deviation =',std_dev)


normalization= (apta - mean)/std_dev
print('Normalization',normalization)

add = np.sum(apta)
print('add = ',add)

[1 2 3 4 5]
mean =  3.0
Sorted = [1 2 3 4 5]
Median = 3.0
Standard deviation = 1.4142135623730951
Normalization [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
add =  15


In [127]:
data =np.array([1,3,4,22,3,2])

print(data[(data>=2)&(data<=8)])


[3 4 3 2]
